### ISSUE TITLE
Basic playlist commands

### ISSUE THREAD

**Issue by RobertAndion** [RobertAndion/DiscordMusicBotNode#2]
In order to have basic functionality for playlists we need to implement the following functions:
- [x] Create a playlist
- [x] Add to playlist
- [x] Delete from playlist (positional value of the song in a playlist)
- [x] Delete playlist
- [x] Play from playlist 
- [x] view playlist
- [x] list playlists

**Comment by LezBianestHere** [comment]
Implemented remaining functions, all basic functions are now complete.
